### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by Muqtxdir** [zarya-os/zarya-common#1]
#### gnome-shell:
- [ ] make panel have static background in overview as well (_does not look good if dock is in panel state_)
- [ ] make selected border of entry fields thinner
- [x] make quick-toggle split much more prominent
- [x] make gdm selected-user color similiar to inkstone from blue_3

#### plymouth:
- [ ] use sed/grep for changing translations correct path
- [ ] add bgrt_fallback logo

#### background:
- [ ] produce backgrounds for zarya (_theme being sunrise for light and sunset for dark_)
- [ ] also maybe depend on gnome-backgrounds?

#### debian:

- [x] add debian packaging
- [x]  add schema override for wallapapers and also include session defaults under separate `zarya-common-defaults`
